---
development:
  cloud_name: hc9gbykil
  api_key: '798355828783145'
  api_secret: _EjHcHir8pgPsp80-37ICGTuu-I
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hc9gbykil
  api_key: '798355828783145'
  api_secret: _EjHcHir8pgPsp80-37ICGTuu-I
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hc9gbykil
  api_key: '798355828783145'
  api_secret: _EjHcHir8pgPsp80-37ICGTuu-I
  enhance_image_tag: true
  static_image_support: false
